// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtBF4ZL2v9cVFcWKD2RwFLSyd3Y-6An8E',
    appId: '1:912710043996:web:05f0bb16078e1b13c55999',
    messagingSenderId: '912710043996',
    projectId: 'cs370-329f4',
    authDomain: 'cs370-329f4.firebaseapp.com',
    storageBucket: 'cs370-329f4.appspot.com',
    measurementId: 'G-VCJF9KEQH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIxGhTa5BXU9OKh8aBx_6zcUJpuHBIWI',
    appId: '1:912710043996:android:d0e2f18eca6deeb9c55999',
    messagingSenderId: '912710043996',
    projectId: 'cs370-329f4',
    storageBucket: 'cs370-329f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmnr3qKNMM97tg4Tw7L7u3x766ccumtg',
    appId: '1:912710043996:ios:08214d67ad2acf58c55999',
    messagingSenderId: '912710043996',
    projectId: 'cs370-329f4',
    storageBucket: 'cs370-329f4.appspot.com',
    iosClientId:
        '912710043996-ftn38uugpdjr5sikmsoaomrvh56saci6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmnr3qKNMM97tg4Tw7L7u3x766ccumtg',
    appId: '1:912710043996:ios:08214d67ad2acf58c55999',
    messagingSenderId: '912710043996',
    projectId: 'cs370-329f4',
    storageBucket: 'cs370-329f4.appspot.com',
    iosClientId:
        '912710043996-ftn38uugpdjr5sikmsoaomrvh56saci6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTutorial',
  );
}
